# Generated by Django 6.0.4 on 2026-05-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
