# Generated by Django 6.0.4 on 2026-04-30 08:12

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('acres', models.IntegerField()),
                ('region', models.CharField()),
                ('city', models.CharField()),
                ('district', models.CharField()),
                ('crop', models.CharField()),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
            ],
        ),
    ]
