# Generated by Django 6.0.4 on 2026-04-30 19:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='region',
            field=models.CharField(choices=[('MARMARA', 'Marmara'), ('KARADENIZ', 'Karadeniz'), ('DOGU_ANADOLU', 'Dogu_anadolu'), ('IC_ANADOLU', 'Ic_anadolu'), ('EGE', 'Ege'), ('AKDENIZ', 'Akdeniz'), ('GUNEY_DOGU_ANADOLU', 'Guney_dogu_anadolu')], max_length=18),
        ),
        migrations.AddIndex(
            model_name='farm',
            index=models.Index(fields=['acres', 'region', 'city', 'district', 'crop', 'location'], name='farm_farm_acres_2046b8_idx'),
        ),
    ]
