# Generated by Django 6.0.4 on 2026-05-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_alter_farm_region_farm_farm_farm_acres_2046b8_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
