# Generated by Django 6.0.4 on 2026-05-02 07:51

import django.db.models.deletion
import farm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_farm_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=farm.models.farmland_image_path)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='farm.farm')),
            ],
        ),
    ]
